package:
    name:           omnipay-interkassa
    namespace:      Omnipay\InterKassa
    headline:       Omnipay: InterKassa
    title:          InterKassa driver for the Omnipay PHP payment processing library
    type:           library
    license:        MIT
    keywords:       php, omnipay, interkassa, merchant, payment
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.

        This package implements [InterKassa](http://interkassa.com/) support for Omnipay.

phpunit:
    colors:

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
