package:
    name:           omnipay-interkassa
    namespace:      Omnipay\InterKassa
    title:          InterKassa driver for the Omnipay PHP payment processing library
    type:           library
    keywords:       php, omnipay, interkassa, merchant, payment
    description:    |
        [InterKassa](http://interkassa.com/) driver for the
        [Omnipay](http://omnipay.thephpleague.com/) PHP payment processing library.

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
